# -*- coding: utf-8 -*-
"""Exp_5A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-5zTvBDrtZE_QKdgWw8MYqNZt_abfoH
"""

!pip install -U langchain langchain-community langchain-text-splitters langchain-huggingface faiss-cpu sentence-transformers

# @title Exp_5A
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS

# STEP 0: Create sample.txt (ADDED ONLY)
with open("sample.txt", "w", encoding="utf-8") as f:
    f.write("""Artificial Intelligence (AI) is a field of computer science that focuses on creating machines capable of performing tasks that typically require human intelligence.

Machine learning is a subset of AI that allows systems to learn from data and improve over time without being explicitly programmed.

Natural Language Processing (NLP) enables computers to understand, interpret, and generate human language.

Deep learning is a specialized area of machine learning that uses neural networks with many layers to analyze complex patterns in data.

AI is widely used in applications such as chatbots, recommendation systems, image recognition, and autonomous vehicles.
""")

# STEP 1: Load
loader = TextLoader("sample.txt", encoding="utf-8")
documents = loader.load()

# STEP 2: Split (UNCHANGED)
splitter = CharacterTextSplitter(
    separator="\n",
    chunk_size=500,
    chunk_overlap=50
)
split_docs = splitter.split_documents(documents)

# STEP 3: Embeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

# STEP 4: FAISS
vectorstore = FAISS.from_documents(
    documents=split_docs,
    embedding=embeddings
)

# STEP 5: Search
query = "What is this document about?"
results = vectorstore.similarity_search(query, k=3)

# STEP 6: Output
for i, doc in enumerate(results, start=1):
    print(f"\nResult {i}")
    print("-" * 50)
    print(doc.page_content)
    print("Metadata:", doc.metadata)